### ISSUE TITLE
Modify the title to add Arabic 

### ISSUE THREAD

**Issue by ghost** [amitdo/Hebrew-OCR-Discussions#1]
Please modify the title to ( Arabic&Hebrew-OCR-Discussions )
Since the Arabic and Hebrew languages share many similarities, including:

- Writing direction Right-to-Left
- Have diacritics, ( Arabic: Tashkil/ Hebrew: Niqqud+geresh and gershayim )

**Comment by amitdo** [comment]
Hi @christophered! 

Although you are right that Hebrew and Arabic share many similarities, I prefer to limit this place to Hebrew only.

Hebrew is my native language, so I think I can help more in questions/discussions about it.

Just to make it clear, I have nothing against Arabic, I just have preferences and priorities in the things I do in my free time.

I'm sorry if my answer disappoints you.

**Comment by ghost** [comment]
It's ok I understand
Thank you for your hard work in the Tesseract project
