### ISSUE TITLE
Tesseract Hebrew Reverse

### ISSUE THREAD

**Issue by idonava** [amitdo/Hebrew-OCR-Discussions#2]
Hello,
When I open my ocr pdf through Adobe and copy the text, All the texts paste results are reversed. 
There is any solution for this problem ?

**Comment by amitdo** [comment]
Hi,

It's a known (unsolved) issue.

One option is to use the Chrome browser to view the pdf flle.
~~Another one is to apply the patch in tesseract issue 238.~~
