### ISSUE TITLE
better results - heb

### ISSUE THREAD

**Issue by jony89** [amitdo/Hebrew-OCR-Discussions#3]
So I've been struggling a lil bit lately with having good results with tesseract 3.05.02 for Hebrew recognition.

I've the following image : 

![srq2921023-0-635924605427104011](https://user-images.githubusercontent.com/16977587/42750215-16b10aee-88ef-11e8-8855-e147034a85d6.jpg)

yet all I get is : 

> ךאת ציר הי\
> 
> \! ו־ `(.
> רביע השבי.
> הוא 12־,
> 'ודה 13
> 

I am using the traindata for 3.05 listed here : https://github.com/tesseract-ocr/tesseract/wiki/Data-Files and tried to grayscale + sharpening the image, which did not give better results.

With that saying, the following [website](https://convertio.co/ocr/) gave me much better result :

![image](https://user-images.githubusercontent.com/16977587/42750768-1b43ce00-88f1-11e8-9085-29f5d6f62265.png)

So do you have any suggestion for me? is there any other tessdata or should I proceed to training myself ?

Also if I do proceed with training is it way better if I move to tesseract 4 ?

**Comment by amitdo** [comment]
Hi @jony89!

Tesseract's image preprocessing step is weak.
You'll need to preprocess the original image, so the shadow will be removed.

Did you try to give tesseract the second image present here?

Training won't help you here.

In general, AFAICT version 4.0 gives better results, but It will have the same issue with the original image.

**Comment by jony89** [comment]
Hey @amitdo , thanks for the response.

Indeed tesseract v4 gives better results, yet the above website is 99% accurate for the following image also (no shadow this time) : 

![b21f3-d7aa1](https://user-images.githubusercontent.com/16977587/42762926-4777c804-891a-11e8-8718-c362a604127b.jpg)

For me, with tesseract v3 and using the following image (after image processing) : 

![b21f3-d7aa1-con - crop](https://user-images.githubusercontent.com/16977587/42762963-635cc498-891a-11e8-90ac-d2a3f436abe5.jpg)

I barely get : 

> 
> נתת גוף הפונקציה 5 * ‎x2 + bx‏ *
> 
>  
> 
> ‎may‏ אוװ(.
> א חשב את שוערה גקװ\ת החותוך שנ גרף
> 
> ‏הםװקצוה עם ‎m‏ ה' ‎x‏ נהנקודרת ‎A‏ ר ‎B‏ בציון}.
> 
> ‏ב חשב את שועװו בקתת החותוך של נוף הפונקציה
> 
> ‏עם צוו ה'צ והנקודה ‎c‏ טווח.
> 
> ‎ 
> 
> ‏ג מצא את המוחק בון הנקודה ‎c‏ נואשות הצוחם.
> ו, מצא את המוחק נון הנקודה וןכנקװה 3).
> 
> ‏ו מצא את המוחק נון הנקודה ‎A‏ כואשות הצווים,

And with tesseract v4 for the same image I get : 

> נתון גרף הפונקציה 5 -1+6%א -
> 
>  
> 
> (ראה ציור).
> 
> א. \חשב את שיעורי נקודות החיתוך של ‎AW‏
> ‏הפונקציה עם ציר ה- א (הנקודות 8 ו- 8 בציור) .
> 
> ב. \ חשב את שיעורי נקודת החיתוך של גרף הפונקציה
> 
> עם ציר ה- ץ (הנקודה ס בציור).
> 
>  
> 
> ג = מצא את המרחק בין הנקודה. ס לראשית הצירים.
> ד. = מצא את המרחק בין הנקודה 8 לנקודה .
> 
> ה. \ מצא את המרחק בין הנקודה . לראשית הצירים,

which is way better but still for some reason it does not recognize the english letters within it allthough this is my command : 

`tesseract b21f3-d7aa1-con.jpg outputbase -l heb+eng`

And using the tessdata here : https://github.com/tesseract-ocr/tessdata for v4


The result of the above website is : 

> נתון גרף הפונקציה 5 ־־* x2 + 6x — ־ y (ראה ציור).
> א.	חשב את שיעורי נקודות החיתוך של גרף הפונקציה עם ציר ה־ x (הנקודות A ו־ B בציור).
> ב.	חשב את שיעורי נקודת החיתוך של גרף הפונקציה עם ציר ה־ y (הנקודה C בציור).
> ג.	מצא את המרחק בין הנקודה C לראשית הצירים.
> ד.	מצא את המרחק בין הנקודה A לנקודה B .
> ה.	מצא את המרחק בין הנקודה A לראשית הצירים.

**Comment by amitdo** [comment]
'-l heb+eng'

Combining two languages does not currently work in 4.0.

You can try the Hebrew.traineddata. It was trained on Hebrew and English.

https://github.com/tesseract-ocr/tessdata_best/raw/master/script/Hebrew.traineddata
Or
https://github.com/tesseract-ocr/tessdata_fast/raw/master/script/Hebrew.traineddata

**Comment by jony89** [comment]
Yeah, tried it as u mentioned it in some other issue, it does get better but not perfectly : 

> נתון גרף הפונקציה 5 -א6+ ?א >
> 
>  (ראה ציור).
> 
> א. חשב את שיעורי נקודות החיתוך של גרף
> הפונקציה עם ציר ה- א (הנקודות ‎A‏ ו- ‎B‏ בציור) .
> 
> ב. חשב את שיעורי נקודת החיתוך של גרף הפונקציה
> 
> עם ציר ה- צ (הנקודה ‏ בציור).
> 
>  ג מצא את המרחק בין הנקודה ‏ לראשית הצירים.
> ד. מצא את המרחק בין הנקודה ‎A‏ לנקודה ‎.B‏
> 
> ה. מצא את המרחק בין הנקודה ‎.A‏ לראשית הצירים.
> 

it replaces x with א

**Comment by amitdo** [comment]
I have no more ideas how to improve the result.

**Comment by jony89** [comment]
OK thanks again for this and for your work here in general.
