### ISSUE TITLE
Line segmentation

### ISSUE THREAD

**Issue by ghost** [amitdo/Hebrew-OCR-Discussions#4]
@amitdo Does Tesseract 4 use `Seam Carving` for text line segmentation?
Example:
https://www.youtube.com/watch?v=h0djlJF-Fsg
https://infoscience.epfl.ch/record/198756/files/ICFHR_2014.pdf
https://ivrl.epfl.ch/research/handwriting_recognition/text_line_extraction

**Comment by amitdo** [comment]
I have no idea, sorry.

**Comment by ghost** [comment]
here you go amitdo, I think seam carving is an interesting method
https://www.cs.bgu.ac.il/~vml/publications/GrayLineExtraction.pdf
https://etd.ohiolink.edu/!etd.send_file?accession=akron1428077337&disposition=inline

https://samosweb.aegean.gr/idips2014/images/stories/arvanitopoulos.pdf
