### ISSUE TITLE
text annotation 

### ISSUE THREAD

**Issue by sivi29y** [amitdo/Hebrew-OCR-Discussions#5]
Hi, is there  a way to activate tesseract on hebrew without annotation?

**Comment by amitdo** [comment]
I'm sorry, I don't understand what you mean here.

**Comment by sivi29y** [comment]
i meant to use tesseract without nikud.
I use it for handwritten capital (דפוס) text and it gives me nikud sometimes even though the text itself is with no nikud.

**Comment by amitdo** [comment]
You can try to use the parameter tessedit_char_blacklist for this purpose.

You'll need a recent version of tesseract.

**Comment by amitdo** [comment]
... from the master branch.

**Comment by sivi29y** [comment]
Ok I'll try .. I also have a list of words that i'm not sure that are in the heb dictionary how can I send to you to train on the public Hebrew set?

**Comment by amitdo** [comment]
I'm sorry. but I'm not going to do any custom training for free.

**Comment by sivi29y** [comment]
Hi Amit,I didn't ask you for training custom data for free. I just think the whole bible text should beon the wordlist really. And i can send you the text and complete wordlist. It is a foundational text for the modern Hebrew language as well. I do not see a benefit in excluding it. And also I can send free link onlineOn Jun 15, 2019 11:40 PM, "Amit D." <notifications@github.com> wrote:I'm sorry. but I'm not going to do any custom training for free.

**Comment by sivi29y** [comment]
anyway this worked on python tesseract 4 

    config = ('-l heb --oem 1 --psm 6 -c tessedit_char_whitelist="אבגדהוזחוטיכלמנסעפצקרשתךםןףץ " ')
